# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.1
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xcku060-ffva1156-2-e ../xilinx_com_hls_krnl_sobel_1_0.zip
