// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xkrnl_sobel.h"

extern XKrnl_sobel_Config XKrnl_sobel_ConfigTable[];

XKrnl_sobel_Config *XKrnl_sobel_LookupConfig(u16 DeviceId) {
	XKrnl_sobel_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XKRNL_SOBEL_NUM_INSTANCES; Index++) {
		if (XKrnl_sobel_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XKrnl_sobel_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XKrnl_sobel_Initialize(XKrnl_sobel *InstancePtr, u16 DeviceId) {
	XKrnl_sobel_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XKrnl_sobel_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XKrnl_sobel_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

