// AUTOGENERATED by Xilinx OpenCL - do not modify

#line 1 "krnl_sobel_compute_unit"
#include "/proj/xbuilds/2016.1_sdaccel_daily_latest/installs/lin64/SDAccel/2016.1/Vivado_HLS/common/technology/autopilot/opencl/libspir_types.h"

#include "/proj/xbuilds/2016.1_sdaccel_daily_latest/installs/lin64/SDAccel/2016.1/Vivado_HLS/common/technology/autopilot/etc/autopilot_ssdm_op.h"
#include "/proj/xbuilds/2016.1_sdaccel_daily_latest/installs/lin64/SDAccel/2016.1/Vivado_HLS/common/technology/autopilot/ap_cint.h"
#define XCL_SIZE_T __spir_size_t

/* KernelID: A, Kernel Name: krnl_sobel */

class aesl_keep_name_class;
typedef struct {
  unsigned int x;
  unsigned int y;
  unsigned int z;
  friend class ::aesl_keep_name_class;
} three_tuple_t;

typedef struct {
  XCL_SIZE_T in_pixels;
  unsigned int nchannels;
  unsigned int width;
  unsigned int height;
  XCL_SIZE_T out_pixels;
  friend class ::aesl_keep_name_class;
} krnl_sobel_args_t;

class aesl_keep_name_class {
public:
  inline __attribute__((always_inline)) static void
  aesl_keep_name_0_args(krnl_sobel_args_t* args) {
    _ssdm_op_SpecExt("member_name", "in_pixels", &args->in_pixels);
    _ssdm_op_SpecExt("member_name", "nchannels", &args->nchannels);
    _ssdm_op_SpecExt("member_name", "width", &args->width);
    _ssdm_op_SpecExt("member_name", "height", &args->height);
    _ssdm_op_SpecExt("member_name", "out_pixels", &args->out_pixels);
  }
};

extern "C" {

extern void __SPIR_kernelA(...);
void __AESL_call_work_itemA(...);

void
__AESL_call_work_item_NA(volatile __attribute__((address_space(16776960))) unsigned int* gmem, __spir_rt_info_t *rt_info, krnl_sobel_args_t *args)
{
  volatile __attribute__((address_space(16776960))) unsigned int *arg_in_pixels = (gmem + ((XCL_SIZE_T)args->in_pixels >> 2));
  unsigned int arg_nchannels = args->nchannels;
  unsigned int arg_width = args->width;
  unsigned int arg_height = args->height;
  volatile __attribute__((address_space(16776960))) unsigned int *arg_out_pixels = (gmem + ((XCL_SIZE_T)args->out_pixels >> 2));
  __SPIR_kernelA(rt_info, arg_in_pixels, arg_nchannels, arg_width, arg_height, arg_out_pixels);
  return;
}

void
__AESL_work_groupA(__attribute__((address_space(16776960))) volatile unsigned int* gmem, krnl_sobel_args_t *args)
{
#define RT_INFO_REQD_LOCAL_SIZE_X 1
#define RT_INFO_REQD_LOCAL_SIZE_Y 1
#define RT_INFO_REQD_LOCAL_SIZE_Z 1
::aesl_keep_name_class::aesl_keep_name_0_args(args);
_ssdm_op_SpecInterface(gmem, "m_axi", 0, 0, 128, 0, "", "", "", 16, 16, 16, 16, "");
_ssdm_op_SpecInterface(0, "s_axilite", 0, 0, 0, 0, "control", "", "", 0, 0, 0, 0, "");
_ssdm_op_SpecInterface(args, "s_axilite", 0, 0, 0, 0, "control", "", "", 0, 0, 0, 0, "");
#define CALL_WORK_ITEM_FUNC __AESL_call_work_itemA
#include "aesl_gen_cu_body.inc"
CALL_WORK_ITEM_FUNC(gmem, &rt_info, args);
#undef  CALL_WORK_ITEM_FUNC
return;
#undef RT_INFO_REQD_LOCAL_SIZE_X
#undef RT_INFO_REQD_LOCAL_SIZE_Y
#undef RT_INFO_REQD_LOCAL_SIZE_Z
}

} // extern C
