# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project krnl_sobel
set_top krnl_sobel
add_files "/proj/picasso/pourya/playground/edge_detection/src/krnl_sobelfilter_pipelined_asyncmem.cl"
open_solution solution_OCL_REGION_0
set_part xcku060-ffva1156-2-e
create_clock -period 200MHz -name default
set_clock_uncertainty 1.350000
config_rtl -register_reset
config_interface -m_axi_addr64
csynth_design -skip_cdt
export_design -format ipxact -kernel_drc -sdaccel
close_project
puts "Vivado HLS completed successfully"
exit
