// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XKRNL_SOBEL_H
#define XKRNL_SOBEL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xkrnl_sobel_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_BaseAddress;
} XKrnl_sobel_Config;
#endif

typedef struct {
    u32 Control_BaseAddress;
    u32 IsReady;
} XKrnl_sobel;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XKrnl_sobel_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XKrnl_sobel_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XKrnl_sobel_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XKrnl_sobel_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XKrnl_sobel_Initialize(XKrnl_sobel *InstancePtr, u16 DeviceId);
XKrnl_sobel_Config* XKrnl_sobel_LookupConfig(u16 DeviceId);
int XKrnl_sobel_CfgInitialize(XKrnl_sobel *InstancePtr, XKrnl_sobel_Config *ConfigPtr);
#else
int XKrnl_sobel_Initialize(XKrnl_sobel *InstancePtr, const char* InstanceName);
int XKrnl_sobel_Release(XKrnl_sobel *InstancePtr);
#endif

void XKrnl_sobel_Start(XKrnl_sobel *InstancePtr);
u32 XKrnl_sobel_IsDone(XKrnl_sobel *InstancePtr);
u32 XKrnl_sobel_IsIdle(XKrnl_sobel *InstancePtr);
u32 XKrnl_sobel_IsReady(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_EnableAutoRestart(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_DisableAutoRestart(XKrnl_sobel *InstancePtr);

void XKrnl_sobel_Set_in_pixels(XKrnl_sobel *InstancePtr, u64 Data);
u64 XKrnl_sobel_Get_in_pixels(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_Set_nchannels(XKrnl_sobel *InstancePtr, u32 Data);
u32 XKrnl_sobel_Get_nchannels(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_Set_width(XKrnl_sobel *InstancePtr, u32 Data);
u32 XKrnl_sobel_Get_width(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_Set_height(XKrnl_sobel *InstancePtr, u32 Data);
u32 XKrnl_sobel_Get_height(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_Set_out_pixels(XKrnl_sobel *InstancePtr, u64 Data);
u64 XKrnl_sobel_Get_out_pixels(XKrnl_sobel *InstancePtr);

void XKrnl_sobel_InterruptGlobalEnable(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_InterruptGlobalDisable(XKrnl_sobel *InstancePtr);
void XKrnl_sobel_InterruptEnable(XKrnl_sobel *InstancePtr, u32 Mask);
void XKrnl_sobel_InterruptDisable(XKrnl_sobel *InstancePtr, u32 Mask);
void XKrnl_sobel_InterruptClear(XKrnl_sobel *InstancePtr, u32 Mask);
u32 XKrnl_sobel_InterruptGetEnabled(XKrnl_sobel *InstancePtr);
u32 XKrnl_sobel_InterruptGetStatus(XKrnl_sobel *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
