// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xkrnl_sobel.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XKrnl_sobel_CfgInitialize(XKrnl_sobel *InstancePtr, XKrnl_sobel_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_BaseAddress = ConfigPtr->Control_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XKrnl_sobel_Start(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL) & 0x80;
    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XKrnl_sobel_IsDone(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XKrnl_sobel_IsIdle(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XKrnl_sobel_IsReady(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XKrnl_sobel_EnableAutoRestart(XKrnl_sobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL, 0x80);
}

void XKrnl_sobel_DisableAutoRestart(XKrnl_sobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_AP_CTRL, 0);
}

void XKrnl_sobel_Set_in_pixels(XKrnl_sobel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IN_PIXELS_DATA, (u32)(Data));
    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IN_PIXELS_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_sobel_Get_in_pixels(XKrnl_sobel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IN_PIXELS_DATA);
    Data += (u64)XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IN_PIXELS_DATA + 4) << 32;
    return Data;
}

void XKrnl_sobel_Set_nchannels(XKrnl_sobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_NCHANNELS_DATA, Data);
}

u32 XKrnl_sobel_Get_nchannels(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_NCHANNELS_DATA);
    return Data;
}

void XKrnl_sobel_Set_width(XKrnl_sobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_WIDTH_DATA, Data);
}

u32 XKrnl_sobel_Get_width(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_WIDTH_DATA);
    return Data;
}

void XKrnl_sobel_Set_height(XKrnl_sobel *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_HEIGHT_DATA, Data);
}

u32 XKrnl_sobel_Get_height(XKrnl_sobel *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_HEIGHT_DATA);
    return Data;
}

void XKrnl_sobel_Set_out_pixels(XKrnl_sobel *InstancePtr, u64 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_OUT_PIXELS_DATA, (u32)(Data));
    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_OUT_PIXELS_DATA + 4, (u32)(Data >> 32));
}

u64 XKrnl_sobel_Get_out_pixels(XKrnl_sobel *InstancePtr) {
    u64 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_OUT_PIXELS_DATA);
    Data += (u64)XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_OUT_PIXELS_DATA + 4) << 32;
    return Data;
}

void XKrnl_sobel_InterruptGlobalEnable(XKrnl_sobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_GIE, 1);
}

void XKrnl_sobel_InterruptGlobalDisable(XKrnl_sobel *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_GIE, 0);
}

void XKrnl_sobel_InterruptEnable(XKrnl_sobel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IER);
    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IER, Register | Mask);
}

void XKrnl_sobel_InterruptDisable(XKrnl_sobel *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IER);
    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IER, Register & (~Mask));
}

void XKrnl_sobel_InterruptClear(XKrnl_sobel *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XKrnl_sobel_WriteReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_ISR, Mask);
}

u32 XKrnl_sobel_InterruptGetEnabled(XKrnl_sobel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_IER);
}

u32 XKrnl_sobel_InterruptGetStatus(XKrnl_sobel *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XKrnl_sobel_ReadReg(InstancePtr->Control_BaseAddress, XKRNL_SOBEL_CONTROL_ADDR_ISR);
}

